### ISSUE TITLE
Reduce verbosity in base models

### ISSUE THREAD

**Issue by Kashuab** [Kashuab/mobx-depot#16]
Every property in a base model class gets these definitions:

```tsx 
  private _firstName?: string;
  get firstName(): string {
    if (this._firstName === undefined) throw new Error('Property firstName is not selected');
    return this._firstName;
  }
  set firstName(value: string) {
    this._firstName = value;
  }
```

I wonder if there's a better way do handle this that would be less verbose. Models with a ton of properties would seem pretty messy, but luckily developers won't be touching the base model.

**Comment by KashubaK** [comment]
Defer error throwing to `Selectable` decorator. Field declarations now look like:

`@Selectable() attackerCharacterIds!: string[];`
