### ISSUE TITLE
Method names in base models could conflict with GraphQL fields

### ISSUE THREAD

**Issue by KashubaK** [Kashuab/mobx-depot#22]
If someone's type has a field with a name within this list:

- `set`
- `selectedData`
- `assign`
- `store`

We could just prefix them with `__`, though I'd hate to have to do `this.__set('name', 'asdf');` everywhere :\ I'd be fine with prefixing the other keys, though.

**Comment by Kashuab** [comment]
There were two routes I could've taken with this:

1. Keep all model data within a `data` property, and offer a `get` method to access the data
2. Prefix auto-generated methods with `_` in cases where an object type has fields that conflict with the auto-generated methods

I'm choosing the latter, as I imagine it'd be pretty rare for this to happen. I don't want to add friction just to address the 0.01% of cases where this happens.

```ts
class BeepBoopBaseModel {
  // This function has a `_` prefix since it conflicts with a GraphQL field.
  _set() {
    // ...
  }
}
```
