### ISSUE TITLE
Generate primitive selectors

### ISSUE THREAD

**Issue by Kashuab** [Kashuab/mobx-depot#25]
One thing that I loved about `mst-gql` was that it generated selectors for primitive fields on each model.

For example, instead of this:

`data => data.token.user(user => user.email.firstName.lastName.createdAt.updatedAt)`

I'd like to do this instead:

`data => data.token.user(userModelPrimitives)`

**Comment by KashubaK** [comment]
Opted for adding a `primitives` key to the selector proxy. This is a better approach as developers won't need to import anything to accomplish this. 

`selectFromUserBaseModel(user => user.primitives.posts(post => post.primitives));`

`primitives` also has some auto-generated documentation that tells you what you'll get:

<img width="233" alt="image" src="https://user-images.githubusercontent.com/7143409/221383437-85324a5d-4e6f-4e6a-b586-9cee833fc65f.png">
