### ISSUE TITLE
Document usage

### ISSUE THREAD

**Issue by KashubaK** [Kashuab/mobx-depot#5]
Developers are going to need to know how to use it! At minimum, provide extensive usage instructions in the `README`.

Ideally this could be done alongside #6, but that would take more time.

**Comment by KashubaK** [comment]
The README has been updated with a lot of docs. There are still some things left to do:

- [ ] New data creation (`useNewInstance`, `store.replace`, etc.)

**Comment by Kashuab** [comment]
I'd rather have multiple issues for specific documentation requirements instead of one blanket issue.
